### ISSUE TITLE
[BUG]: 官网文档打开失败

### ISSUE THREAD

**Issue by zhang-chuanfeng** [tkeel-io/tkeel#182]
### What happened?

![image](https://user-images.githubusercontent.com/59160162/164199657-dae29b90-44a2-466a-b0ee-4d3e98a1960e.png)

### Version

latest (main)

### What OS are you seeing the problem on?

Windows11 x86

### Other

None

### Code of Conduct

- [X] I agree to follow this project

**Comment by chanoe** [comment]
@zhang-chuanfeng  try https://docs.tkeel.io/
