### ISSUE TITLE
[BUG]: check tenant list , unexpected end of JSON input

### ISSUE THREAD

**Issue by lunz1207** [tkeel-io/tkeel#23]
### What happened?

```
tkeel tenant list -k
❌  unexpected end of JSON input
```

### Version

0.1.0 (Default)

### What OS are you seeing the problem on?

macos

### Relevant log output

ime="2021-10-22T01:47:30.86316388Z" level=debug msg="route succ." instance=keel-654dcf5798-b58pm scope=keel.plugin.keel type=log ver=unknown
time="2021-10-22T01:47:30.86390638Z" level=debug msg="route pID() requst /auth/tenant/list" instance=keel-654dcf5798-b58pm scope=keel.plugin.keel type=log ver=unknown
time="2021-10-22T01:47:30.863973755Z" level=debug msg="upstreamPath: tenant/list" instance=keel-654dcf5798-b58pm scope=keel.plugin.keel type=log ver=unknown
time="2021-10-22T01:47:30.864986338Z" level=debug msg="plugin route(tenant) is not registered" instance=keel-654dcf5798-b58pm scope=keel.keel type=log ver=unknown
time="2021-10-22T01:47:30.865056547Z" level=error msg="error check plugin(tenant) status: not registered" instance=keel-654dcf5798-b58pm scope=keel.plugin.keel type=log ver=unknown

### Other

None

### Code of Conduct

- [ ] I agree to follow this project

**Comment by OdysseusC** [comment]
## 原因
在外部流量访问的 URL 中新增了依赖版本的检查，cli 调用时为指定版本号。
## 解决方案
检查版本号是否合法，如不合法则直接返回，cli 添加对应版本号。

**Comment by imneov** [comment]
对于版本应该前置校验比较好，cli版本与平台版本一致即可
