### ISSUE TITLE
[proprosal] About the PKG layout

### ISSUE THREAD

**Issue by OdysseusC** [tkeel-io/tkeel#39]
I want to change the layout like this:
```
xxx
├── charts
├── cmd
│   └── xxx
├── docker
├── docs
│   ├── decision_records
│   ├── development
│   └── release_notes
├── pkg
│   ├── apis(proto自动生成)
│   ├── server
│   │   ├── grpc(转换，很薄的一层去调用具体的逻辑service) //  func() (ctx context.Context, in pb.XXX)(out,error)) error
│   │   └── http(转换，很薄的一层去调用具体的逻辑service) //  func() (ctx context.Context, reqIn) error
|   ├── service(错误判断之类的，处理相同的输入输出的)
│   │   └── xxx(调用Models里面的oprator完成具体的逻辑)
│   ├── models
│   │   ├── aaa
│   │   └── bbb
│   │       ├── xxx.go (用到的数据结构 和oprator interface)
│   │       └── xxx.go (对这个interface的实现)
│   ├── errcode
│   ├── logger
│   ├── utils
│   ├── proto
│   └── version
├── tests
├── proto
└── tools

```
View and modify the [design document](https://docs.google.com/document/d/153ltyIkEYOV7klYo-JHekYhRMcnleu08ZZk5Jus5UZA/edit?usp=sharing).

**Comment by uptutu** [comment]
I have some comments as follows.
1. remove the plural form of the folder name, as long as it is still a Go package
2. remove the `pkg/utils` file, this part is the same as the upper `tool` folder

**Comment by OdysseusC** [comment]
> I have some comments as follows.
> 
> 1. remove the plural form of the folder name, as long as it is still a Go package
> 2. remove the `pkg/utils` file, this part is the same as the upper `tool` folder

1. 去掉复数这个可以有。
2. `pkg/utils` 这个包和外层的 `tool` 我理解并没有重复，`pkg/utils` 这个是 go 包及 go 代码中所需要用到的，tool 里面可能回事一些工具例如一些可用的代码生成器或者某些可执行的脚本这样的东西。

**Comment by OdysseusC** [comment]
关于目录结构暂定为如此，新的目录结构按照 [tkeel-template-go](https://github.com/tkeel-io/tkeel-template-go) 模板，tkeel v0.2.0 将会在模板的基础上进行开发。
