### ISSUE TITLE
[proposal] About test framework

### ISSUE THREAD

**Issue by liuzhen21** [tkeel-io/tkeel#40]
1. [goconvey](https://github.com/smartystreets/goconvey)
2. [testify](https://github.com/stretchr/testify)

reference：
[vs](https://knapsackpro.com/testing_frameworks/difference_between/goconvey/vs/go-testify)

**Comment by guoj-a** [comment]
Let's compare：
1. GoConvey
2. GoStub
3. GoMock
4. Monkey

**Comment by guoj-a** [comment]
Let's compare：

1. GoConvey
2. GoStub
3. GoMock
4. Monkey

**Comment by uptutu** [comment]
I propose to use [gomonkey](https://github.com/agiledragon/gomonkey) for the mock

**Comment by guoj-a** [comment]
Take a look at this：

1. GoConvey
2. GoStub
3. GoMock
4. Monkey

https://www.jianshu.com/p/e3b2b1194830

**Comment by uptutu** [comment]
I prefer :
Test Framework: [testify](https://github.com/stretchr/testify)
Mock: [gomonkey](https://github.com/agiledragon/gomonkey) + [gomock](https://github.com/golang/mock)

That's enough.

**Comment by imneov** [comment]
E2E：
- https://github.com/dapr/dapr/blob/master/.github/workflows/kind-e2e.yaml
- https://github.com/kubesphere/kubesphere/blob/master/.github/workflows/kind/kind.yaml

**Comment by imneov** [comment]
It's better to add some sample code

@uptutu @guoj-a

**Comment by imneov** [comment]
testify：
```
  assert.Equal(t, 123, 123, "they should be equal")
  assert.NotEqual(t, 123, 456, "they should not be equal")
```


goconvey:
```
assert.So(expr, should.NotBeNil)
assert.So(err, should.BeNil)
```

**Comment by uptutu** [comment]
> testify：
> 
> ```
>   assert.Equal(t, 123, 123, "they should be equal")
>   assert.NotEqual(t, 123, 456, "they should not be equal")
> ```
> 
> goconvey:
> 
> ```
> assert.So(expr, should.NotBeNil)
> assert.So(err, should.BeNil)
> ```

Here are the major differences between the two.

`testify` is a more traditional testing framework, with 'assertions' that are common to other programming languages

`goconvey` is a BDD (Behavior-driven development) testing framework.
The same BDD framework is also available: [ginkgo](https://github.com/onsi/ginkgo) 

Most libraries use `testify` and that's what I think.
