### ISSUE TITLE
[feat] Overview of the feature design of the Repository

### ISSUE THREAD

**Issue by uptutu** [tkeel-io/tkeel#43]
<h2>Repository</h2>
<p>仓库（repository）是 tKeel 中管理插件的一个重要组件，主要用于拉取指定云端仓库（helm 仓库）的所有插件列表，并提供相应插件的 chart 管理（列表，安装，卸载）接口。</p>

<h3>安装一个插件的流程</h3>

[![plugin-install-v0-2-0.png](https://i.postimg.cc/mZcxQWzP/plugin-install-v0-2-0.png)](https://postimg.cc/jCrkb9hT)

<h3>实现细节</h3>
<p>基于 helm 进行封装，对用户暴露更友好体验的用户安装。</p>

<p>用户可以配置一个私有 helm 仓库用作可安装插件管理的发现地址，集成一个官方仓库。也就是说可查询到的所有插件：</p>
<pre><code class="language-Bash">$ helm repo search
</code></pre>
<h3>API</h3>

<del>
> 注释：因为重新架构和 helm 依赖安全问题，取消了自定义远程仓库的设计。
> 如果需要，开发者可以通过  **配置文件** 实现。
</del>

<h4>添加仓库地址</h4>
<p>添加私有仓库至 tKeel 平台，为 Helm 配置可用的私有仓库，安装自己已有的插件。</p>
<p>自定义的添加的仓库地址仅能配置一个，该配置可用在启动 tKeel 平台时配置。</p>
<p><code>PUT</code>     <code>/repos</code></p>
<p><strong>Parameters</strong></p>

  |   |   |  
-- | -- | -- | --
Name | Type | In | Description
addr | string | body | <b>Required.</b> <br>The address of the chart repository that the user wants the platform to pull.

<p><strong>实现逻辑：</strong></p>
<p>通过 API 拿到用户想要添加的仓库地址，采用 k8s 的 ConfigMap 覆盖掉原有处叫做「custom_repo_addr」的地址信息。</p>

<h4>插件列表</h4>
<p>获取当前所有可安装至平台的插件。</p>
<p><code>GET</code>     <code>/plugins</code></p>
<p><strong>实现逻辑：</strong></p>
<p>通过封装 helm 的查询接口，并将 helm 查询到的所有可用的 chart 信息返回。</p>
<pre><code class="language-Bash">$ helm repo update
$ helm search repo
</code></pre>
<p><strong>Parameters</strong></p>

|  |   |   |   |
| -- | -- | -- | --|
| Name | Type | In | Description |
| type | string | query | <b>Required.</b> <br>Either 'installable', 'installed', can be used. |

<del>
<h4>指定仓库的插件列表</h4>
<p>获取当前所有可安装至平台的插件。</p>
<p><code>GET</code>     <code>/repos/{repo}/plugins</code></p>
<p><strong>实现逻辑：</strong></p>
<p>通过封装 helm 的查询接口，并将 helm 查询到的所有可用的 chart 信息返回。</p>
<pre><code class="language-Bash">$ helm repo update {repo}
$ helm search {repo}
</code></pre>
</del>

<h4>安装插件</h4>
<p>通过指定名称安装对应的插件至平台。</p>
<p><code>POST</code>     <code>/plugins</code></p>
<p><strong>Parameters</strong></p>

  |   |   |  
-- | -- | -- | --
Name | Type | In | Description
repo | string | body | <b>Required.</b><br>Point to the specific repository where the plugin is locatedThat
chart | string | body | <b>Required.</b><br>Name of the plugin to be installed
name | string | body | <b>Required.</b><br>Name specified after successful installation

<p><strong>实现逻辑</strong></p>
<p>拿到指定的仓库名和插件名使用 helm 进行安装。</p>
<pre><code class="language-Bash">$ helm install {instance_name} {repo}/{name}
</code></pre>
<h4>卸载插件</h4>
<p>通过指定实例名（instance_name）删除对应的实例安装。</p>
<p><code>DELETE</code>    <code>/plugins/{name}</code></p>
<p><strong>Parameters</strong></p>

  |   |   |  
-- | -- | -- | --
Name | Type | In | Description
name | string | query | <b>Required.</b> <br> The name is what instance you want to delete.

**Comment by uptutu** [comment]
<h2>补充 </h2> 

<h3> Deprecated </h3>

根据  2021 年 11 月 15 日 下午的讨论，_仓库_ 还需要支持 **插件上传** 的功能。也就是说平台还需要有一套文件管理系统用于管理用户自己的插件。

<h3>设计方案</h3>

基于 heml 的插件安装方式，我想到了两种管理 chart 的方式：
1. 使用本地 tgz 文件安装式
2. 采用远程仓库式

<h4> tgz 本地安装式 </h4>

如果采用本地安装，那么我们需要在系统中设计文件管理系统，用于管理当前每一个用户上传上来的 chart 包（tgz 文件）。
优点：可以完全自控，功能自由定义，灵活性大。
缺点：文件关联依赖数据库，分布式设计难题，安全性等都需要考虑进去，大工程，耗时久。
p.s: 即使使用官方文档的本地创建一个 heml 仓库，在 PaaS 平台实现仓库所需 API ，将 chart 存在本地也需要考虑分布式问题。

<h4> 采用远程仓库 </h4> 

不能采用一个公有云服务器为大量用户提供自由的上传满足用户自身需求，成本太大。
因此，为用户搭建一个自己的私有远程仓库是最合适的。资源可以由用户自由定义。

<h4>总结</h4>

最后决定，采用远程仓库式，在平台启动的同时起一个仓库服务，根据官方文档推荐，选择使用  [ChartMuseum]( https://chartmuseum.com/docs/#using-with-local-filesystem-storage/)   作为本地远程仓库的文件管理系统管理用户自己的 _plugin chart_ 

<h4>重新设计后的架构流程图</h4>

因为新功能的需要，重新设计了整个流程，如下图示：

[![plugin-install-v0-2-0-v1.png](https://i.postimg.cc/Tw578Y8t/plugin-install-v0-2-0-v1.png)](https://postimg.cc/WFj6gV1Z)

Refs:

[The Chart Repository Guide](https://helm.sh/docs/topics/chart_repository/)

**Comment by uptutu** [comment]
# 再补充
根据 2021 年 11 月 23 日晨会同步，希望仓库更小更轻便，所以最后结论是恢复第一版的设计。

平台依赖私有 helm 仓库，但不提供私有仓库的管理等功能，由用户提供私有仓库地址，自由上传插件至自己的私有仓库，平台紧提供将应用安装至平台一起的 Pod 与命名空间中。

**Comment by OdysseusC** [comment]
# 再补充
根据重构后的 tKeel 仓库里代码结构和对 repo 的设计理念，以及插件在平台中生命周期的概念，将部分插件的逻辑和生命周期移动至仓库管理中。

repo 中提供的接口将在第一版的基础上进行部分修改。


## model
repo:
```go
type PluginRepo struct {
	URL  string `json:"url,omitempty"`  // repo url.
	Name string `json:"name,omitempty"` // repo name,no duplication allowed.
	UpsertTimestamp int64 `json:"upsert_time_stamp,omitempty"` // last upsert time stamp.
}
```
存储与 `model/plugin` 相同，存储至 dapr 的 private state 中。

plugin:
```go
type Plugin struct {
	ID                string                          `json:"id,omitempty"`                 // plugin id.
        // add repo name.
	Repo              string                          `json:"repo,omitempty"`               // plugin repo.

	PluginVersion     string                          `json:"plugin_version,omitempty"`     // plugin version.
	TkeelVersion      string                          `json:"tkeel_version,omitempty"`      // plugin depend tkeel version.
	AddonsPoint       []*openapi_v1.AddonsPoint       `json:"addons_point,omitempty"`       // plugin declares addons.
	ImplementedPlugin []*openapi_v1.ImplementedPlugin `json:"implemented_plugin,omitempty"` // plugin implemented plugin list.
	Secret            string                          `json:"secret,omitempty"`             // plugin registered secret.
	RegisterTimestamp int64                           `json:"register_timestamp,omitempty"` // register timestamp.
	ActiveTenantes    []string                        `json:"active_tenantes,omitempty"`    // active tenant id list.
	Version           string                          `json:"version,omitempty"`            // model version.
}
```
在原有结构中添加 repo 字段，记录插件的仓库信息。存储时，key 为 “REPO/ID” 格式拼接。

将 `model/plugin/AllPlugins` => `model/plugin/AllRegisterPlugins`。仅存储已注册插件。

## API
repo中包含：
* GET /repos：列出已添加的仓库。
* POST /repos/{repo_name}：添加新仓库。
* DELETE /repos/{repo_name}：删除仓库。

> 
> ### 实现细节
> 基于 helm 进行封装，对用户暴露更友好体验的用户安装。
> 
> 用户可以配置一个私有 helm 仓库用作可安装插件管理的发现地址，集成一个官方仓库。也就是说可查询到的所有插件：
> 
> ```
> $ helm repo search
> ```
> 
> ### API
> ~ > 注释：因为重新架构和 helm 依赖安全问题，取消了自定义远程仓库的设计。 > 如果需要，开发者可以通过 **配置文件** 实现。 ~
> #### 添加仓库地址
> 添加私有仓库至 tKeel 平台，为 Helm 配置可用的私有仓库，安装自己已有的插件。
> 
> 自定义的添加的仓库地址仅能配置一个，该配置可用在启动 tKeel 平台时配置。
> 
> `PUT` `/repos`
> 
> **Parameters**
> 
>  	 	 	 
> Name	Type	In	Description
> addr	string	body	Required.
> The address of the chart repository that the user wants the platform to pull.
> **实现逻辑：**
> 
> 通过 API 拿到用户想要添加的仓库地址，采用 k8s 的 ConfigMap 覆盖掉原有处叫做「custom_repo_addr」的地址信息。
> 
> #### 插件列表
> 获取当前所有可安装至平台的插件。
> 
> `GET` `/plugins`
> 
> **实现逻辑：**
> 
> 通过封装 helm 的查询接口，并将 helm 查询到的所有可用的 chart 信息返回。
> 
> ```
> $ helm repo update
> $ helm search repo
> ```
> 
> **Parameters**
> 
> Name	Type	In	Description
> type	string	query	Required.
> Either 'installable', 'installed', can be used.~ #### 指定仓库的插件列表 获取当前所有可安装至平台的插件。 `GET` `/repos/{repo}/plugins` **实现逻辑：** 通过封装 helm 的查询接口，并将 helm 查询到的所有可用的 chart 信息返回。 ``` $ helm repo update {repo} $ helm search {repo} ``` ~
> #### 安装插件
> 通过指定名称安装对应的插件至平台。
> 
> `POST` `/plugins`
> 
> **Parameters**
> 
>  	 	 	 
> Name	Type	In	Description
> repo	string	body	Required.
> Point to the specific repository where the plugin is locatedThat
> chart	string	body	Required.
> Name of the plugin to be installed
> name	string	body	Required.
> Name specified after successful installation
> **实现逻辑**
> 
> 拿到指定的仓库名和插件名使用 helm 进行安装。
> 
> ```
> $ helm install {instance_name} {repo}/{name}
> ```
> 
> #### 卸载插件
> 通过指定实例名（instance_name）删除对应的实例安装。
> 
> `DELETE` `/plugins/{name}`
> 
> **Parameters**
> 
>  	 	 	 
> Name	Type	In	Description
> name	string	query	Required.
> The name is what instance you want to delete.

**Comment by OdysseusC** [comment]
# 设计修改
根据重构后的 tKeel 仓库里代码结构和对 repo 的设计理念，以及插件在平台中生命周期的概念，将部分插件的逻辑和生命周期移动至仓库管理中。将 CLI 中对于插件的安装和卸载功能集成到 rudder 中。并沿用 CLI 中对于插件生命周期的定义。

```
      developer         +        paas manager         +     tantent manager
                        |                             |
   +------------+       |       +-----------+         |      +----------+
   |            |       |       |           |         |      |          |
   | developing |       |       | published |         |      | disabled |
   |            |       |       |           |         |      |          |
   +----+-------+       |       +---+-------+         |      +---+------+
        |               |   install |                 |          |
        |  ^            |           v   ^             |          | ^
        |  |            |               | uninstall   |          | |
        |  |            |       +-------+---+         |          | |
release |  |            |       |           |         |   enable | |
        |  | upgrade    |       | installed |         |          | | disable
        |  |            |       |           |         |          | |
        |  |            |       +---+-------+         |          | |
        |  |            |  register |                 |          | |
        v  |            |           v  ^              |          v |
           |            |              | unregister       |            |
   +-------+----+       |       +------+----+         |      +-----+----+
   |            |       |       |           |         |      |          |
   |  release   |       |       |registered |         |      | enabled  |
   |            |       |       |           |         |      |          |
   +------------+       +       +-----------+         +      +----------+

```

repo 中提供的接口将在第一版的基础上进行部分修改，将安装、注册、卸载、删除接口进行规范和重定义。

通过 InfoOprator、Repository 和 Installer 三个 interface 的抽象，来将底层仓库具体的实现形式和存储进行隔离。

[![repo-design-drawio.png](https://i.postimg.cc/Pr1Hg9bs/repo-design-drawio.png)](https://postimg.cc/8jkxWynt)

> 未定逻辑：初版 Repository 和 Installer 以 Helm 的为基础实现（Helm Repo 实现 Repository，Helm Chart 对应 Installer），安装时利用 Kustomize 添加 dapr 相关的 annotations，可以通过 Configuration 中 inject_dapr 这个值决定这一动作是否执行。

## repository
主要包含对仓库、安装包和中心的定义，中心对于仓库的管理逻辑。

### Repository, Installer, InfoOperator, Constructor and DestoryPlugin
将仓库和安装包进行抽象：

* Repository（仓库）：
1. 获取仓库信息即获取 `repository.Info`。
2. 根据传入的字符，搜索与之匹配的安装包名称。
3. 获取指定的名称和版本的安装包。
4. 查询已安装的安装包。
5. 关闭仓库。

* Installer（安装包）：
1. 设置安装的插件 ID。
2. 获取安装包注释。
3. 获取安装包设置项。
4. 设置安装包设置项。
5. 安装安装包。
6. 卸载由此安装包安装的插件。
7. 获取安装包简要信息。

* InfoOperator（仓库信息操作员）：
* 根据传入的 `repository.Info` 存储。
* 查询指定名称的 `repository.Info`。
* 删除指定名称的 `repository.Info`。
* 列出存储的所有 `repository.Info`。
* 当存储的 `repository.Info` 发生变化时，调用传入的回调函数。


将仓库的构造函数进行抽象：
* 提供根据 `repository.Info` 初始化一个 Repository 对象的能力。

将仓库对于插件的销毁函数进行抽象：
* 提供删除指定名称插件的函数能力。


```go
// Annotations json object.
type Annotations map[string]interface{}

// Options key and value.
type Option struct {
	Key   string      `json:"key"`
	Value interface{} `json:"value"`
}

// InstallerBrief installer brief information.
type InstallerBrief struct {
	Name      string `json:"name"`
	Repo      string `json:"repo"`
	Version   string `json:"version"`
	Installed bool   `json:"installed"`
}

// Installer plugin installer.
type Installer interface {
	// SetPluginID set plugin id after installing to tKeel.
	SetPluginID(pluginID string)
	// Annotations get annotations.custom datas.  Return a copy of the Annotations.
	Annotations() Annotations
	// Options get installer options.
	Options() []Option
	// SetOption set installer option.
	SetOption(...*Option) error
	// Install install plugin.
	Install() error
	// Uninstall Uninstall plugin.
	Uninstall(pluginID string) error
	// Brief get installer brief information.
	Brief() *InstallerBrief
}

// Info repository information.
type Info struct {
	Name        string      `json:"name"`                  // repository name.
	URL         string      `json:"url"`                   // repository url.
	Annotations Annotations `json:"annotations,omitempty"` // repository annotations.
}

// InfoOperator manager repository information operator.
type InfoOperator interface {
	// create plugin repo.
	Create(context.Context, *Info) error
	// Update plugin repo.
	Update(context.Context, *Info) error
	// Get plugin repo info with the repo name.
	Get(ctx context.Context, repoName string) (*Info, error)
	// Delete plugin repo with the repo name.
	Delete(ctx context.Context, repoName string) (*Info, error)
	// List get all plugin repo.
	List(ctx context.Context) ([]*Info, error)
	// Watch plugin repo map change. parameter is the changed data.
	Watch(ctx context.Context, interval string, callback func(news, updates, deletes []*Info) error) error
}

// Repository plugin installer repository.
type Repository interface {
	// Info get repository information.
	Info() *Info
	// Search for installers whose names match words. * match all installers.
	Search(word string) ([]*InstallerBrief, error)
	// Get the installer with matching name and version.
	Get(name, version string) (Installer, error)
	// Installed find installed installer(contains installation packages that have been deleted in the repository).
	Installed() []Installer
	// Close close this repository.
	Close() error
}

// Constructor return new repository.
type Constructor func(connectInfo *Info, args ...interface{}) (Repository, error)

// DestoryPlugin destory model.Plugin.
type DestoryPlugin func(pluginID string) error
```

### Hub
拥有管理多个仓库的组件。

* 初始化：用单例创建一个 Hub 并在初始化时读取已经存储的 `repository/Info` 通过传入的构造函数去构造出 `repository/Repository` 对象，存入全局的 Hub 中。创建一个 watch 的协程。

* watch：监听存储的 `repository/Info`，当有变化时，将会返回具体变化的数据，并对变化的数据进行处理。

* 新增：通过传入的参数新增一个 `repository/Info` 结构体并通过此结构体构造出 `repository/Repository` 对象，存入全局的 Hub 中，并持久化 `repository/Info`。

* 删除：Hub 中删除指定名称的仓库，同时删除对应的 `repository/Info`。

* 查询：根据名称返回查询到的 `repository/Repository` 实例。

* 插件卸载：删除传入的插件名称，类似于控制面板级别的删除程序，逻辑为调用 repository 中已安装的接口查询是否存在已将安装的安装包，如果有，调用对应安装包的卸载，如果没有则直接执行初始化时传入的销毁函数把插件卸载掉。

## model

### 存储的数据
prepo 的 Oprator 应提供 对于 `model/PluginRepo` 的 CRUD。

具体的对象结构暂定如下。

```go
type PluginRepoMap map[string]*PluginRepo

type PluginRepo struct {
	Name            string `json:"name,omitempty"`              // repo name,no duplication allowed.
	URL             string `json:"url,omitempty"`               // repo url.
	UpsertTimestamp int64  `json:"upsert_time_stamp,omitempty"` // last upsert time stamp.
}

// Operator contains all operations to plugin repo.
type Operator interface {
	// Model2Info model.PluginRepo convert to repository.Info.
	Model2Info(*model.PluginRepo) *repository.Info
	// Info2Model repository.Info convert to model.PluginRepo.
	Info2Model(*repository.Info) *model.PluginRepo
	// GetChanges compare the old and the new one and get the new, update and delete.
	GetChanges(old, curr model.PluginRepoMap) (new, update, delete []*model.PluginRepo)
	// repository info.
	repository.InfoOperator
}

```

在原有 `model/Plugin` 中添加 installer 字段(`repository.InstallerBrief`)，记录插件的安装包信息。

将 `model/plugin/AllPlugins` => `model/plugin/AllRegisterPlugins`。仅存储已注册插件。

增加 `model/PluginRepo` 和 `model/PluginRepoMap`。存储添加的仓库信息和所有已添加的仓库。

`model/PluginRepo` 初版存储与 `model/plugin` 相同，存储至 dapr 的 private state 中。

`model/proute/Operator` 在实际场景中，数据量不会太多，一般存储的仓库源不会超过10个。

## API
### repo
repo中包含：

* GET /repos：列出已添加的仓库。

response:
```json
[
	{
		"name":"xxx",
		"url":"http://xxx",
		"timestamp":12315,
	}
]
```
* POST /repos/{repo_name}：添加新仓库。

request body:
```json
{
	"url":"http://xxx",
}
```
response:
```json
{
	"name":"xxx",
	"url":"http://xxx",
	"timestamp":12315,
}
```
* DELETE /repos/{repo_name}：删除仓库。

response:
```json
{
	"name":"xxx",
	"url":"http://xxx",
	"timestamp":12315,
}
```
* GET /repos/{repo_name}/installer：列出当前仓库的所有安装包。

response:
```json
{
	"installers":[
		{
			"name":"abc",
			"version":"v0.3.0",
                        “repo”:"xxx",
			"installed":false
		}
	]
}
```
* GET /repos/{repo_name}/installers/{installer_name}/{installer_version}：查询指定名称的安装包，返回注释和对应的安装配置项及默认值。

response:
```json
{
	"installer":
		{
			"name":"abc",
			"version":"v0.3.0",
                        “repo”:"xxx",
			"annotations":[
				{
					"key":"foo",
					"value":"boo",
					"desc":"annotation describetion."
				}
			],
			"readme":"", // file byte.
			"configuration_schema":"", // schema file.
			"schema_type": 0, // schema type enum.
			"configuration":"" // configuration file.
		}
}
```

### plugins
plugins 中新增和修改：

* POST /plugins/{id}：安装插件。

request:
```json
{
	"installer_info":{
		"name":"installer name",
		"version":"installer version",
		"repo_name":"installer repo name",
		"configuration":"installer configuations file", // file bytes.
		"type":"installer configuartion file format type"
	}
}
```
response:
```json
{
	"plugin":{
		"id":"plugin id",
		"status":1
	}
}
```

* DELETE /plugins/{id}：卸载插件。

response:
```json
{
	"plugin":{
		"id":"plugin id",
		.
		.
		.
	}
}
```

* ~POST /plugins：注册插件。~ POST /plugins/{id}/register：注册插件。

request
```json
{
	"secret":{
		"data":"changeme"
	}
}
```

* DELETE /plugins/{id}/register：注销插件。

response:
```json
{
	"plugin":{
		"id":"plugin id",
		.
		.
		.
	}
}
```
