### ISSUE TITLE
[refactory] tkeel v0.2.0 design decision

### ISSUE THREAD

**Issue by OdysseusC** [tkeel-io/tkeel#44]
基于 v0.1.0 版本的开发，我们验证了 tkeel 平台插件机制的可行性即 **OPENAPI** 机制加上 helm 包管理的插件机制的可行性。

为了平台的后续开发和文档等功能的开发，团队成员设计了一套新的开发流程，将可生成的代码块进行抽象，选择更加便捷的 HTTP 开源库，同时为了完善 tkeel-io 下仓库代码的一致性和平台的统一性，将 tkeel 仓库中现有代码按照 [tkeel-template-go](https://github.com/tkeel-io/tkeel-template-go) 的结构进行调整。

为了最终整个平台形态呈现的统一和整体性，将现有的插件化设计进行调整，核心插件改为组件形态，直接通过 HTTP 或 GRPC 接口调用，无需实现 **OPENAPI** 规范，详细设计见[此文档](https://github.com/tkeel-io/tkeel/blob/main/docs/decision_records/architecture/ARC-001-core-plugin-componentization.md).

tkeel v0.2.0 将会在继承 v0.1.0 版本已实现的功能的基础上进行代码重构和部分逻辑修改，具体为以下几点：

1. tkeel 中 Plugins 插件改为 Manager 组件，Keel 插件改为 Keel 组件，Auth 插件改为 Security 组件并独立出来，Core 插件包为组件形态统一由平台提供服务，即平台代理 Core 中对外的 API。
2. ~~manager 将后端存储改为 Core 进行存储，动态路由等功能基于 Core 给予的实体即关系等能力实现。~~ Core 暂不支持，故仍选择 dapr 的 state 进行存储。
3. 新增 Repository 管理，Repository 相关介绍见 #43 。
4. 将 **OPENAPI** 定义改为 通过 protobuf 定义且移至 [kit](https://github.com/tkeel-io/kit) 仓库中。
5. 将现有 [cli](https://github.com/tkeel-io/cli) 中部分功能集成到 Manager 组件的 Repository 管理能力中。

**Comment by imneov** [comment]
LGTM ~

**Comment by OdysseusC** [comment]
Done.
