### ISSUE TITLE
[suggest] cmd remove init func mode

### ISSUE THREAD

**Issue by uptutu** [tkeel-io/tkeel#47]
While there is not a lot of code under `/cmd` now, I would like to change the way I use `init()` to load subcommands under `/cmd` to a controlled declarative call.

**Comment by imneov** [comment]
**Simple to understand is greater than concise.**

Using `init()` should be a general paradigm, tkeel's `/cmd` is just a special case. I think it would be better to keep this paradigm.

https://github.com/tkeel-io/tkeel-interface/blob/main/tool/cmd/artisan/proto/proto.go

**Comment by uptutu** [comment]
I have made the following research from the official [list](https://github.com/spf13/cobra/blob/master/projects_using_cobra.md)

## Is this project use `init()` add subcommand paradigm?
Click to jump to the evidence I found.

❎ [arduino-cli ](https://github.com/arduino/arduino-cli/blob/master/cli/cli.go)

✅ [bleve ](https://github.com/blevesearch/bleve/blob/master/cmd/bleve/cmd/create.go)

✅ [cockroach](https://github.com/cockroachdb/cockroach/blob/master/pkg/ccl/workloadccl/cliccl/fixtures.go)

❎ [cosmos](https://github.com/cosmos/cosmos-sdk/blob/76dde985364729222a53df33ffe14a0f60d46b7a/simapp/simd/cmd/root.go#L144)

❎ [datree](https://github.com/datreeio/datree/blob/main/cmd/root.go#L41)

❎ [etcd](https://github.com/etcd-io/etcd/blob/main/etcdctl/ctlv3/ctl.go#L77)

❎ [helm](https://github.com/helm/helm/blob/dd0177aed71dd3c5b044e25c55870cd66f0f05fa/cmd/helm/root.go#L167)

❎ [istio](https://github.com/istio/istio/blob/master/istioctl/cmd/root.go#L218)

❎ [uber/prototool](https://github.com/uber/prototool/blob/dev/internal/cmd/cmd.go#L102)

❎ [k8s cmd](https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-proxy/app/server.go)

❎ [hugo cmd](https://github.com/gohugoio/hugo/blob/master/commands/version.go)

❎ [golangci-lint](https://github.com/golangci/golangci-lint/blob/b67af9afb993a5d2f5a47eafe2848d144c2fc09a/pkg/commands/run.go#L288)

## Why should avoid `init()`
Using `init()` may lead to some unexpected results and should be avoided

It seems to me that using `init()` to register commands in our `cmd` does not have to do this, and it would make the code clearer to use an obvious centralised declaration of registration in the entry process.

### ref：
[the-problems-of-go-init-func](https://www.leyafo.com/2021-07-07-the-problems-of-go-init-func/)
[uber-go/guide: avoid-init](https://github.com/uber-go/guide/blob/master/style.md#avoid-init)

## Conclusion
As you can see, most of the best projects avoid using `init` to do some complex logic.
