### ISSUE TITLE
[feat] tKeel authorization design

### ISSUE THREAD

**Issue by OdysseusC** [tkeel-io/tkeel#61]
### What Is Your Expect

现在的 tKeel 中无法保证租户和用户信息在插件间调用时正确传递。

当前为携带了租户和用户信息的外部请求到 keel 后通过了鉴权，然后以透传的方式将 token 透传给后续上游服务中。仅仅只能让信息传递到一个插件中，如果需要在后续调用链中有效传递，在现在的规范中没有定义相关的做法。

根据上述问题，做出了以下设计来解决它。

## Design

在 Keel 处将外部访问进行鉴权处理，并写入头 `x-tKeel-auth` 中，`x-tKeel-auth` 中存储 ~JSON Object~ KV 键值对 并以 Base64 加密:
~`{"src":"plugin_id","tenant":"tenant_id","user":"user_id","role":"role"}`~~`src=plugin_id&`~`tenant=tenant_id&user=user_id&role=role`。后续访问中必须带上此头。

~src 中预留 ID：**_tKeel**，表示请求由系统发起，从 Keel 或 Rudder 发出，用于 Rudder 访问 OpenAPI 时使用。~
* tenant 中预留 ID：**_tKeel_system**，表示请求直接由系统发起。
* user 中预留 ID：**_tKeel_admin**，请求直接由系统发起。
* role 中预留字段：**admin**，表示角色为租户下的管理员。

[![auth-design-drawio.png](https://i.postimg.cc/PJpRGxsY/auth-design-drawio.png)](https://postimg.cc/m14wCTrg)

插件获取当前访问的租户和用户信息时仅需解析 `x-tKeel-auth` 头信息即可，且需要对上述各字段的预留 ID 进行处理。

通过 Keel 访问管理平台也会解析对应的 token 并写入 `x-tKeel-auth` 中，填入信息均为上述预留 ID 即 ~`{"src":"_tKeel","tenant":"_tKeel_system","user":"_tKeel_admin"}`~~`src=_tKeel&`~`tenant=_tKeel_system&user=_tKeel_admin&role=admin`

在内部访问时，Keel 检查 HTTP 请求必须携带有效的 `x-tKeel-auth` 以此来强制要求插件间调用的合法性。

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by imneov** [comment]
go-sdk does not support http-header.

1. Consider adding similar options to go-sdk, like [net-sdk](https://github.com/dapr/dotnet-sdk/)

2. Define a message format (the problem is that it is too intrusive)



Ref:
https://github.com/dapr/dotnet-sdk/issues/512
https://github.com/search?q=org%3Adapr+HttpInvocationOptions&type=issues

**Comment by imneov** [comment]
https://github.com/dapr/dotnet-sdk/issues/526

When adding options to go-sdk, we need to consider HTTP and gRPC.
