### ISSUE TITLE
[FEAT_REQUEST]: Optimize the plugin registration process

### ISSUE THREAD

**Issue by OdysseusC** [tkeel-io/tkeel#82]
## 背景
现有的插件注册流程和设计有出入，注册操作未能隐式完成，设计注册和安装操作分离的原因就是为了确保插件在正常运行的情况下 *rudder* 再去调用 `/v1/identify` 接口，来确保插件的信息能够成功加载进 tKeel 平台中。

现有设计使前端并不支持此步骤，考虑 rudder 自动完成此流程。

## 解决方案

[![plugin-register-unregister-drawio.png](https://i.postimg.cc/Wz6CRCx0/plugin-register-unregister-drawio.png)](https://postimg.cc/y3xvcQ1N)

修改插件状态仅为 installed 和 register。

当插件安装后，拉起一个 **goroutine** 不定时的监听插件的 `/v1/status` 接口，当接口返回 **Running** 时，访问插件的 `/v1/identify` 接口，获取对应信息完成注册流程。

插件卸载时，判断所有租户均停用插件，再删除路由表信息和对应的插件信息。

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by OdysseusC** [comment]
删除了现有的 /v1/{plugin_id}/register 接口

**Comment by imneov** [comment]
> 删除了现有的 /v1/{plugin_id}/register 接口

如果 helm 安装后需要 register 怎么办？
